### PR TITLE
feat(connector): provide prev state slice to target (function)

### PR DESCRIPTION
**Pull request by AKolodeev**
Hi! First of all, thank you for your work! This library is really useful.  

Sometimes I pass a callback function as target and I need to compare previous state slice with a new one. I can achieve this such way:
```javascript
import { pick } from 'lodash';

mergeToTarget(nextState, actions) {
  const prevState = pick(this, Object.keys(nextState));

  if (prevState.foo !== nextState.foo) {
    this.handleFooChange(nextState.foo);
  }

  Object.assign(this, nextState);
  Object.assign(this, actions);
}
```
But I sure it can be achieved much more easily.

In this PR I provide previous state slice as third argument for target function.
For initial update I provide `undefined`.

Also, I fixed store reducer in `connector.spec.js`: because of redux initial action `defaultState.baz` would be `undefined` instead of `-1`.

### CODE REVIEW

**Comment by AKolodeev** [comment]
@AntJanus? Or somebody?

**Comment by AntJanus** [comment]
I'm a fan of this but I'm wondering if there is an equivalent in the react-redux library. My vision for `ng-redux` has been to provide as much parity as possible without providing many extra features.

**Comment by AntJanus** [comment]
Sorry for the late response on this. Work + kids have kept me busy and unable to dedicate my time to the library. I'm hoping to pick it back up after the holidays! :)

**Comment by AKolodeev** [comment]
React components have `componentWillReceiveProps`\`componentDidReceiveProps` hooks which will get next props include props from `mapStateToProps` function and have access to previous props. In AngularJS app we can't use $onChanges hook to detect state changes caused by mapStateToTarget function. So I think, the most convenient way is provide prevState in mapStateToTarget.

Thank you for answer :)

**Comment by AntJanus** [comment]
@AKolodeev fantastic! I'll put it on my todo list to test this out and I'll merge it in as soon as I can.

**Comment by AKolodeev** [comment]
Fixed conflicts. @AntJanus will you merge it? :)

**Pull request merged**
