### PR TITLE
switch to babel transform runtime Fixes #152

### LINKED ISSUE #152: 3.5.0 fails in PhantomJS without Object.assign polyfill
FYI

As lodash assign method was replaced by Object.assign all tests using phantomjs as browser start to fail. 
`TypeError: undefined is not a constructor (evaluating 'assign({}, store, { connect: Connector(store) })') `

Can be fixed by downgrading to 3.4.1 or using [phantomjs-polyfill-object-assign](https://www.npmjs.com/package/phantomjs-polyfill-object-assign)

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
3.5.0 broke this package in IE because Object.assign isn't variable. You need to enable transform-runtime to automatically shim the feature.

**Comment by graingert** [comment]
Fixes #152

**Comment by graingert** [comment]
@deini ^

**Comment by deini** [comment]
Looks good, can you remove the /dist changes please? We will push them when we cut a new release.

**Comment by graingert** [comment]
@deini rebased and fixed. Looking forward to getting the dist files git-ignored in v4

**Comment by deini** [comment]
Me too @graingert , thanks for updating this.

**Comment by graingert** [comment]
@deini any chance of a release?

**Comment by deini** [comment]
@graingert I don't have npm access yet. I'll bug @AntJanus tomorrow :)

**Comment by graingert** [comment]
or @wbuchwalter

**Comment by AntJanus** [comment]
@deini I'm about to do a release. Thanks! :)

**Comment by graingert** [comment]
@AntJanus @deini it looks like transform-runtime didn't run when transpiling

**Comment by graingert** [comment]
@AntJanus @deini it looks like transform-runtime didn't run when transpiling...

**Comment by graingert** [comment]
@AntJanus @deini ok I've got a fix here: https://github.com/angular-redux/ng-redux/pull/162

**Pull request merged**
